### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/tim/workspaces_wx/Age-Gender-Pred-master/models/res18_cls70_best.nn'

### ISSUE THREAD

**Issue by chenyuqing** [adamzjk/Age-Gender-Pred#4]
FileNotFoundError: [Errno 2] No such file or directory: '/home/tim/workspaces_wx/Age-Gender-Pred-master/models/res18_cls70_best.nn'

**Comment by naayaaa** [comment]
you should train your network before loading weight file

**Comment by mehdikhanahmadzadeh** [comment]
i also encouter this error .
i dont want train the model .
i just want predict some image by your model 
could you please help me
